version: "3.7"

services:
  newcentury-nginx:
    hostname: nginx
    container_name: newcentury-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/var/www/sju-nlp
    depends_on:
      - sju-nlp-backend
      - sju-nlp-database
  sju-nlp-backend:
    build: .
    image: sju-nlp-ai-music-player:latest
    container_name: sju-nlp-backend
    restart: always
    ports:
      - "8005:8080"
    volumes:
      - ./storage:/app/data
      - ./logs:/app/logs
    depends_on:
      - sju-nlp-database
  sju-nlp-database:
    image: mysql:8.0.26
    container_name: sju-nlp-database
    restart: always
    ports:
      - "9005:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    volumes:
      - ./database:/var/lib/mysql
